# Generated by Django 3.1.6 on 2021-02-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_tagged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
