# Generated by Django 3.1.6 on 2021-02-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
